name: Validate PR Title to MAIN

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Search updated PR title
        id: get-pr-title
        run: |
          PR_TITLE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.title')

          echo "PR Title: $PR_TITLE"
          echo "pr_title=$PR_TITLE" >> $GITHUB_ENV

      - name: Checking PR title
        run: |
          if [[ ! "${{ env.pr_title }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: The PR title must follow the pattern 'vX.Y.Z' (exemplo: v1.2.3)."
            exit 1
          fi